# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lenovo/tb351fu/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/tb351fu

PRODUCT_COPY_FILES += \

PRODUCT_PACKAGES += \
    NetworkStackResOverlay \
    TetheringResOverlay \
    LTHD \
    NonFrameworkLbs \
    AndroidDeveloperVerifier \
    CrossDeviceServices \
    FamilyLinkParentalControls \
    GWP \
    LFHTianjiaoTablet \
    PersonalSafety \
    SearchSelector \
    SettingsIntelligence \
    Turbo \
    ZuiGameHelper \
    ATMWifiMeta \
    BatteryWarning \
    # DebugLoggerUI \
    LocationEM2 \
    MiraVision \
    mediatek-res \
    CallRecorderService \
    DataChannelService \
    EmergencyInfoGms \
    FMRadio \
    MtkGbaService \
    MtkSettingsProvider \
    SimProcessor \
    StorageManager \
    VoiceCommand \
    VoiceUnlock \
    WallpaperCropper \
    daxService \
    PenService \
    CustomPropInterface \
    DataChannelApi \
    SatelliteClient \
    com.android.extensions.appfunctions \
    log-handler \
    mediatek-carrier-config-manager \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-services \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    BuildManifestSystemExt \
    mtk-mbrainj-default.xml
